=== VVKMulukutla/FML/bookinfo.dtd
<!ELEMENT bookinfo (title, author, isbn, publisher, pubdate, edition, price)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT pubdate (#PCDATA)>
<!ELEMENT edition (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ATTLIST price currency CDATA #REQUIRED>

=== VVKMulukutla/FML/bookinfo.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE bookinfo SYSTEM "bookinfo.dtd">
<bookinfo>
    <title>PHP and MySQL Web Development</title>
    <author>Luke Welling</author>
    <isbn>0-672-32672-8</isbn>
    <publisher>Sams Publishing</publisher>
    <pubdate>2003</pubdate>
    <edition>Second</edition>
    <price currency="USD">39.99</price>
</bookinfo>
